services:
  - type: web
    name: binance-tv-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: BINANCE_API_KEY
        value: your_binance_testnet_api_key
      - key: BINANCE_SECRET_KEY
        value: your_binance_testnet_secret_key
      - key: SYMBOL
        value: BTCUSDT
      - key: ORDER_QTY
        value: 0.001
